### PR TITLE
fix: fix navigation when going back and forth in history on web

### LINKED ISSUE #9128: Web - Navigation is broken after going back and forth
**Current Behavior**

Here's the demo [from the blog ](https://reactnavigation.org/blog/2020/05/16/web-support)

web-broken

**Expected Behavior**

The navigation to not be broken.

**How to reproduce**

Doing the following actions will break the navigation stack on web:
1. backward
2. forward
3. backward again
4. Now the navigation is broken. You cannot go backward or forward anymore.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       | 5.8.10
| @react-navigation/stack        | 5.12.8

### PR DESCRIPTION
**Pull request by satya164**
closes #9408
fixes #9128

### CODE REVIEW

**Comment by AlastairTaft** [comment]
Copying over my comment from [here](https://github.com/react-navigation/react-navigation/issues/9128#issuecomment-941908166)

I now hit this error

error

version

File: packages/native/src/useLinking.tsx [hunk 1]
```diff
@@ -98,12 +98,16 @@ const createMemoryHistory = () => {
...
+        //   the first item. We need to keep only the new updated object, otherwise it will break
+        //   the page when navigating forward in history.
+        // - This is the first time any state modifications are done
+        //   So we need to push the entry as there's nothing to replace
+        items = [{ path, state, id }];
       } else {
-        // This is the first time any state modifications are done
-        // So we need to push the entry as there's nothing to replace
-        items.push({ path, state, id });
+        items[index] = { path, state, id };
```
Comment (roryabraham) [inline packages/native/src/useLinking.tsx:110]: Because we're seeing [this error](https://github.com/react-navigation/react-navigation/pull/9970#issuecomment-941908688), that tells us that somehow the `items` array is actually getting in a state where it contains `undefined`.

Now, there's only four places the `items` array is written to: [line 84](https://github.com/react-navigation/react-navigation/blob/fb84805c889bbb7059e7e95592c004aea2a510d6/packages/native/src/useLinking.tsx#L84), [line 86](https://github.com/react-navigation/react-navigation/blob/fb84805c889bbb7059e7e95592c004aea2a510d6/packages/native/src/useLinking.tsx#L86), [line 108](https://github.com/react-navigation/react-navigation/blob/fb84805c889bbb7059e7e95592c004aea2a510d6/packages/native/src/useLinking.tsx#L108), and [line 110](https://github.com/react-navigation/react-navigation/blob/fb84805c889bbb7059e7e95592c004aea2a510d6/packages/native/src/useLinking.tsx#L110).

Reviewing these 1 by 1:

#### Line 84
`items = items.slice(0, index - 1)` -> I don't see any way this can add an `undefined` value to the array ❌ 

#### Line 86
`items.push({ path, state, id })` -> At worst, this could append an object like: `{path: undefined, state: undefined, id: undefined}`, but we wouldn't end up with `undefined` itself in the `items` array. So not here either ❌ 

#### Line 108
`items = [{ path, state, id }];` -> Similar to line 86, this can't cause `undefined` to be in the `items` array ❌ 

#### Line 110
`items[index] = { path, state, id };` -> This _can_ cause `undefined` to be in the `items` array if `index` is greater than the length of the array, like so:

```js
> let items = [];
undefined
> items[1] = 'Hello';
'Hello'
> items[0];
undefined
```

Comment (roryabraham) [reply packages/native/src/useLinking.tsx:110]: How the `index` is somehow becoming greater than the length of the `item` array? I do not know
