### PR TITLE
fix(drawer): fix drawer clearing interaction handle

### LINKED ISSUE #10337: InteractionManager.runAfterInteractions triggers only first time with @react-navigation/drawer@6.3.1
### Current behavior

InteractionManager.runAfterInteractions triggers only first time you visit the screen

### Expected behavior

InteractionManager.runAfterInteractions triggers each time you visit the screen

### Reproduction

https://snack.expo.dev/gUhhNNxT3

- Press Navigate
- Accept alert
- Go back
- Press Navigate
- Alert is not triggered anymore from useEffect InteractionManager.runAfterInteractions

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

https://snack.expo.dev/gUhhNNxT3

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.8
| @react-navigation/bottom-tabs          | 6.2.0
| @react-navigation/drawer               | 6.3.1
| @react-navigation/material-top-tabs    | 6.1.1
| @react-navigation/stack                | 6.1.1
| react-native-safe-area-context         | 3.3.2
| react-native-screens                   | 3.8.0
| react-native-gesture-handler           | 1.10.2
| react-native-reanimated                | 2.2.0
| react-native-tab-view                  | 3.1.1
| react-native-pager-view                | 5.4.6
| react-native                           | 0.67.2
| expo                                   | 43.0.0

### PR DESCRIPTION
**Pull request by ricmatsui**
Please provide enough information so that others can review your pull request:

**Motivation**

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Fixes #10337. The modern drawer implementation is leaking `InteractionManager` interaction handles. This causes other code that relies on [runAfterInteractions](https://reactnative.dev/docs/interactionmanager#runafterinteractions) to not run.

Currently, the interaction handle is created `onStart` of `useAnimatedGestureHandler` and only cleared `onEnd`. However, `onEnd` is not guaranteed to be called based on the [state flows](https://docs.swmansion.com/react-native-gesture-handler/docs/under-the-hood/states-events#state-flows). The gesture may enter a failed or cancelled state instead of ended, and `onEnd` is then not called: [useAnimatedGestureHandler source](https://github.com/software-mansion/react-native-reanimated/blob/e25d29aa689a1442d298927303473da44a07d475/src/reanimated2/hook/useAnimatedGestureHandler.ts#L54)

This PR fixes this issue by clearing the interaction handle `onFinish` which is guaranteed to be called after `onStart`.

**Test plan**

Demonstrate the code is solid. Example: the exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Make sure you test on both platforms if your change affects both platforms.

The code must pass tests.

```
git apply test.patch
```

<details>
  <summary>Contents of test.patch</summary>

```diff
diff --git a/packages/drawer/src/views/modern/Drawer.tsx b/packages/drawer/src/views/modern/Drawer.tsx
index 20d3f7bc..796ff513 100644
--- a/packages/drawer/src/views/modern/Drawer.tsx
+++ b/packages/drawer/src/views/modern/Drawer.tsx
@@ -35,6 +35,8 @@ const minmax = (value: number, start: number, end: number) => {
   return Math.min(Math.max(value, start), end);
 };
 
+let count = 0;
+
 export default function Drawer({
   dimensions,
   drawerPosition,
@@ -107,11 +109,13 @@ export default function Drawer({
   const interactionHandleRef = React.useRef<number | null>(null);
 
   const startInteraction = () => {
+    console.log('start', ++count);
     interactionHandleRef.current = InteractionManager.createInteractionHandle();
   };
 
   const endInteraction = () => {
     if (interactionHandleRef.current != null) {
+      console.log('end', --count);
       InteractionManager.clearInteractionHandle(interactionHandleRef.current);
       interactionHandleRef.current = null;
     }
```
</details>

```
yarn example start
```

Before:

https://user-images.githubusercontent.com/5288285/157349249-9c29c301-dce8-486f-ac3f-14d3ac2eae61.mov

After:

https://user-images.githubusercontent.com/5288285/157349085-3f6b5436-5a60-4a3f-a6db-5950234dcacf.mov

**Code formatting**

Look around. Match the style of the rest of the codebase. Run `yarn lint --fix` before committing.

### CODE REVIEW

File: packages/drawer/src/views/modern/Drawer.tsx [hunk 1]
```diff
@@ -210,7 +210,9 @@ export default function Drawer({
           : open;
 
       toggleDrawer(nextOpen, event.velocityX);
-      runOnJS(onGestureEnd)();
+    },
+    onFinish: () => {
+      runOnJS(onGestureFinish)();
```
Comment (vonovak) [inline packages/drawer/src/views/modern/Drawer.tsx:215]: thanks for the PR. Maybe `onGestureFinish` does not need to exists and we just call `endInteraction` here?

Comment (ricmatsui) [reply packages/drawer/src/views/modern/Drawer.tsx:215]: Thanks @vonovak, I think it is good as is since the `onGestureFinish` JS callback matches `onGestureStart`. Both callbacks existed before this PR, and I only renamed `onGestureEnd` to `onGestureFinish`.

Let me know we should remove `onGestureFinish` and only call `endInteraction` here and I will make the change.

**Review by satya164 — APPROVED** [review]
Thank you
